### ISSUE TITLE
priv folder contents not copied to device

### ISSUE THREAD

**Issue by noozo** [lucaong/elixir_bme680#4]
Hi, first of all thanks for the work on this, i greatly appreciate it.

I was compiling and deploying to my device (nerves) and noticed that the 2 binaries in priv do not get copied to my device (resulting in enoent when trying to start the genserver). 

Either i'm doing something wrong or your lib might be suffering from something similar to this: https://github.com/fhunleth/elixir_ale/issues/6

I think because your binaries are generated when the lib gets compiled, they are somehow not copied. Only when i remove the priv folder from the build directory and deploy again (i.e. firmware) it does get copied over.

Cheers,
Pedro

**Comment by lucaong** [comment]
Hi @nocivus , thanks for reporting this. It might well be the same issue as `ElixirALE` indeed, I will look into it.

**Comment by lucaong** [comment]
I think updating `elixir_make` should fix this. It's probably related to the issue fixed by [this commit](https://github.com/elixir-lang/elixir_make/commit/c4fdb586b5ca2a01b3d3d0b8e1c12ae53397df32). I'll update and release a new version. @nocivus, if you could check if that solves it for you, it would be great!

**Comment by lucaong** [comment]
I published version `v0.2.1`, using the latest `elixir_make`, that should fix this issue.
